experiment_name: 'd_Identity_resample_r'
train_on_shortest_path: False  # make sure it works when this is the case
resample: True # @param
wandb_on: True
seed: 45
grid: False
dist_cutoff: 10
n_std_dist_cutoff: 5
plot: True

feature_position: False  # make sure it works when this is the case
weighted: False

num_hidden: 160 # @param
num_layers: 1  # @param
num_message_passing_steps: 2  # @param
learning_rate: 0.00001 # @param
num_training_steps: 100000 # @param
residual: True
layer_norm: False

# Env Stuff
batch_size: 2
nx_min: 12
nx_max: 14

batch_size_test: 4
nx_min_test: 12
nx_max_test: 14
