experiment_name: 'Learn identity no resample with Feature position '
train_on_shortest_path: True  # make sure it works when this is the case
resample: False # @param
wandb_on: False
seed: 42

feature_position: False  # make sure it works when this is the case
weighted: False

num_hidden: 500 # @param
num_layers: 2  # @param
num_message_passing_steps: 3  # @param
learning_rate: 0.001 # @param
num_training_steps: 200 # @param

# Env Stuff
batch_size: 6
nx_min: 2
nx_max: 6

batch_size_test: 6
nx_min_test: 2
nx_max_test: 6
