experiment_name: 'Identity_l'
train_on_shortest_path: False  # make sure it works when this is the case
resample: False # @param
wandb_on: True
seed: 45

feature_position: False  # make sure it works when this is the case
weighted: False

num_hidden: 160 # @param
num_layers: 1  # @param
num_message_passing_steps: 2  # @param
learning_rate: 0.00001 # @param
num_training_steps: 300 # @param
residual: False
layer_norm: True

# Env Stuff
batch_size: 2
nx_min: 5
nx_max: 6

batch_size_test: 4
nx_min_test: 5
nx_max_test: 6