experiment_name: 'Learn identity no resample with Feature position '
train_on_shortest_path: True  # make sure it works when this is the case
resample: True # @param
wandb_on: False
seed: 45

feature_position: False  # make sure it works when this is the case
weighted: False

num_hidden: 160 # @param
num_layers: 1  # @param
num_message_passing_steps: 2  # @param
learning_rate: 0.0001 # @param
num_training_steps: 200 # @param

# Env Stuff
batch_size: 2
nx_min: 5
nx_max: 6

batch_size_test: 2
nx_min_test: 5
nx_max_test: 6