experiment_name: 'train_on_shortest_path'
train_on_shortest_path: True  # make sure it works when this is the case
resample: True # @param
wandb_on: False
seed: 42

feature_position: False   # make sure it works when this is the case
weighted: False

num_hidden: 500 # @param
num_layers: 2  # @param
num_message_passing_steps: 4  # @param
learning_rate: 0.001 # @param
num_training_steps: 300 # @param


# Env Stuff
batch_size: 4
nx_min: 3
nx_max: 5

batch_size_test: 4
nx_min_test: 3
nx_max_test: 5
