experiment_name: 'train_on_shortest_path'
train_on_shortest_path: True
resample: True # @param
wandb_on: True
seed: 41

feature_position: False
weighted: False

num_hidden: 100 # @param
num_layers: 2  # @param
num_message_passing_steps: 3  # @param
learning_rate: 0.001 # @param
num_training_steps: 400 # @param


# Env Stuff
batch_size: 4
nx_min: 3
nx_max: 5

batch_size_test: 4
nx_min_test: 3
nx_max_test: 5
