experiment_name: 'Learn identity no resample with Feature position '
train_on_shortest_path: True   # make sure it works when this is the case
resample: True # @param
wandb_on: False
seed: 42

feature_position: False  # make sure it works when this is the case
weighted: True

num_hidden: 300 # @param
num_layers: 2  # @param
num_message_passing_steps: 5  # @param
learning_rate: 0.0001 # @param
num_training_steps: 10 # @param

# Env Stuff
batch_size: 2
nx_min: 2
nx_max: 3

batch_size_test: 2
nx_min_test: 2
nx_max_test: 3