plot_config:
  trajectory_plot:
    figure_size: (8, 6)
    trajectory_colormap: "plasma"
    trajectory_alpha: 0.6
    external_wall_color: "C3"
    external_wall_thickness: 3
    custom_wall_color: "C0"
    custom_wall_thickness: 3
    scatter_alpha: 0.6
    scatter_marker: "o"
    scatter_marker_size: 0.1
    label_fontsize: 24
    tick_label_fontsize: 12
    plot_every_points: 20
    grid: True

  ratemap_plot:
    figure_size: (8, 6)
    ratemap_colormap: "jet"
    bin_size: 2.0
    label_fontsize: 24
    tick_label_fontsize: 12
    colorbar_label_fontsize: 12
