wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696200011.413785
    t:
      1:
      - 1
      - 5
      - 12
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: darwin-x86_64
