experiment_name: 'random_mp_0'
wandb_on: False
seed: 45
plot: True
dataset: 'random'  # 'random' or 'omniglot' or positional'positional_no_edges

num_hidden: 15 # @param
num_layers: 1  # @param
num_message_passing_steps: 0  # @param which is effectivly 5
learning_rate: 0.001 # @param
num_training_steps: 15000 # @param
residual: True

# Env Stuff
batch_size: 2
num_nodes_max: 15
num_features: 1
batch_size_test:  2
num_nodes_max_test: [4,5,6,7,8,10]

